//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_level_1to9_H
#define METASPRITE_level_1to9_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_1to9_TILE_ORIGIN 0
#define level_1to9_TILE_W 8
#define level_1to9_TILE_H 8
#define level_1to9_WIDTH 112
#define level_1to9_HEIGHT 88
#define level_1to9_TILE_COUNT 27
#define level_1to9_PALETTE_COUNT 2
#define level_1to9_COLORS_PER_PALETTE 4
#define level_1to9_TOTAL_COLORS 8
#define level_1to9_MAP_ATTRIBUTES 0
extern const unsigned char level_1to9_map[154];
#define level_1to9_map_attributes level_1to9_map

BANKREF_EXTERN(level_1to9)

extern const palette_color_t level_1to9_palettes[8];
extern const uint8_t level_1to9_tiles[432];

#endif
