//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_snake_main_site_H
#define METASPRITE_snake_main_site_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define snake_main_site_TILE_ORIGIN 0
#define snake_main_site_TILE_W 8
#define snake_main_site_TILE_H 8
#define snake_main_site_WIDTH 160
#define snake_main_site_HEIGHT 144
#define snake_main_site_TILE_COUNT 44
#define snake_main_site_PALETTE_COUNT 1
#define snake_main_site_COLORS_PER_PALETTE 4
#define snake_main_site_TOTAL_COLORS 4
#define snake_main_site_MAP_ATTRIBUTES 0
extern const unsigned char snake_main_site_map[360];
#define snake_main_site_map_attributes snake_main_site_map

BANKREF_EXTERN(snake_main_site)

extern const palette_color_t snake_main_site_palettes[4];
extern const uint8_t snake_main_site_tiles[704];

#endif
