/*

 SNAKE_BCKG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\sja\Programming\GB_dev\GBTD\snake_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __snake_bckg_h_INCLUDE
#define __snake_bckg_h_INCLUDE

#define snake_bckgWidth 20
#define snake_bckgHeight 18
#define snake_bckgBank 0

extern const unsigned char snake_bckg[];

#endif

/* End of SNAKE_BCKG.H */
