//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_splash_bg_asset_H
#define METASPRITE_splash_bg_asset_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define splash_bg_asset_TILE_ORIGIN 0
#define splash_bg_asset_TILE_W 8
#define splash_bg_asset_TILE_H 8
#define splash_bg_asset_WIDTH 160
#define splash_bg_asset_HEIGHT 120
#define splash_bg_asset_TILE_COUNT 255
#define splash_bg_asset_PALETTE_COUNT 1
#define splash_bg_asset_COLORS_PER_PALETTE 4
#define splash_bg_asset_TOTAL_COLORS 4
#define splash_bg_asset_MAP_ATTRIBUTES 0
extern const unsigned char splash_bg_asset_map[300];
#define splash_bg_asset_map_attributes splash_bg_asset_map

BANKREF_EXTERN(splash_bg_asset)

extern const palette_color_t splash_bg_asset_palettes[4];
extern const uint8_t splash_bg_asset_tiles[4080];

#endif
