//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_top_score_border_H
#define METASPRITE_top_score_border_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define top_score_border_TILE_ORIGIN 28
#define top_score_border_TILE_W 8
#define top_score_border_TILE_H 8
#define top_score_border_WIDTH 160
#define top_score_border_HEIGHT 32
#define top_score_border_TILE_COUNT 34
#define top_score_border_PALETTE_COUNT 2
#define top_score_border_COLORS_PER_PALETTE 4
#define top_score_border_TOTAL_COLORS 8
#define top_score_border_MAP_ATTRIBUTES 0
extern const unsigned char top_score_border_map[80];
#define top_score_border_map_attributes top_score_border_map

BANKREF_EXTERN(top_score_border)

extern const palette_color_t top_score_border_palettes[8];
extern const uint8_t top_score_border_tiles[544];

#endif
