/*

 SNAKE_BODY_DOWN.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __snake_body_down_h_INCLUDE
#define __snake_body_down_h_INCLUDE

/* Bank of tiles. */
#define snake_body_downBank 0
/* Start of tile array. */
extern const unsigned char snake_body_down[];

#endif

/* End of SNAKE_BODY_DOWN.H */
