/*

 SNAKE_CORNER_DOWN_RIGHT.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char snake_corner_d_r[] =
{
  0x00,0x00,0x00,0x00,0x0F,0x0F,0x0F,0x0F,
  0x33,0x33,0x33,0x33,0x3C,0x3C,0x3C,0x3C
};

/* End of SNAKE_CORNER_DOWN_RIGHT.C */
