/*

 SNAKE_EATEN_DOWN.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char snake_eaten_down[] =
{
  0x3C,0x3C,0x3C,0x3C,0xF3,0xF3,0xF3,0xF3,
  0xCF,0xCF,0xCF,0xCF,0x3C,0x3C,0x3C,0x3C
};

/* End of SNAKE_EATEN_DOWN.C */
