/*

 SNAKE_HEAD_FOOD_D.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __snake_head_food_d_h_INCLUDE
#define __snake_head_food_d_h_INCLUDE

/* Bank of tiles. */
#define snake_head_food_d.cBank 0
/* Start of tile array. */
extern const unsigned char snake_head_food_d.c[];

#endif

/* End of SNAKE_HEAD_FOOD_D.H */
